language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
install:
  - npm install

env:
  global:
    - NODE_ENV=test

script:
  - docker build -t orbiseed-test .
  - npm ci
  - npm run test
notifications:
  email: false
